spring:
  application:
    name: analysis
  kafka:
    bootstrap-servers: 192.168.1.12:9092
    consumer:
      group-id: first-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 7777
  servlet:
    context-path: /${spring.application.name}
log.home: /data/dao-data-logs/${spring.application.name}
