server:
  port: 7777
  servlet:
    context-path: /analysis
spring:
  kafka:
    bootstrap-servers: 192.168.1.8:9092
    consumer:
      group-id: first-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer