log.home: /data/dao-data/dot-record
server:
  port: 7771
  servlet:
    context-path: /dot-record
spring:
  kafka:
    bootstrap-servers: 192.168.1.9:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer